### ISSUE TITLE
Add link to the demo on the repo page

### ISSUE THREAD

**Issue by jtpio** [DerThorsten/xeus-javascript#11]
### Description

Currently there is no link in the top-right area of the repo to easily try the kernel: 

![image](https://github.com/jupyter-xeus/xeus-javascript/assets/591645/5ccc1ea8-25e3-49cf-924e-9e8d41e2aaef)

It would be nice to add one!

**Comment by DerThorsten** [comment]
I just gave you write permission @jtpio, feel free to make any cosmetic change you want =)

**Comment by jtpio** [comment]
Thanks @DerThorsten.

However I don't seem to be able to do it, the gear icon is still missing:

![image](https://github.com/jupyter-xeus/xeus-javascript/assets/591645/d64ba153-2363-4822-9cf7-f1ac48232589)

**Comment by jtpio** [comment]
It may require `Maintain` permissions.

**Comment by DerThorsten** [comment]
> It may require `Maintain` permissions.

done

**Comment by jtpio** [comment]
Done, thanks!
