### ISSUE TITLE
"update_display_data" function needed

### ISSUE THREAD

**Issue by MRYingLEE** [DerThorsten/xeus-javascript#13]
So far, only a few kernel messaging functions are defined and exposed:

    emscripten::function("_publish_stdout_stream", &xeus_javascript::publish_stdout_stream);
    emscripten::function("_publish_stderr_stream", &xeus_javascript::publish_stderr_stream);
    emscripten::function("_display_data", &xeus_javascript::display_data); 

Can you define and expose other messaging related functions, especially "update_display_data"?

I tried at https://github.com/MRYingLEE/xeus-javascript/blob/9baef04eaf850894b8bb06205beedbd1638f0df4/src/xinterpreter.cpp#L61.

But the building didn't work for technical issue, which is not familiar to me.

Thank you.

**Comment by DerThorsten** [comment]
Sure, we can expose this. Feel free to open a PR if you already started to work on that

**Comment by DerThorsten** [comment]
done in #12

**Comment by MRYingLEE** [comment]
Something wrong with output functions after this commit.
Even no output for console.log, such as:
console.log("Hello");

I tested in different browsers.
Please check.

**Comment by DerThorsten** [comment]
> Something wrong with output functions after this commit. Even no output for console.log, such as: console.log("Hello");
> 
> I tested in different browsers. Please check.

even tough you are right, I would appreciate a less commanding tone

**Comment by DerThorsten** [comment]
> Something wrong with output functions after this commit. Even no output for console.log, such as: console.log("Hello");
> 
> I tested in different browsers. Please check.

I reverted the pr and fixed/updated it with https://github.com/jupyter-xeus/xeus-javascript/pull/15
