### ISSUE TITLE
console.log() output to other cells

### ISSUE THREAD

**Issue by MRYingLEE** [DerThorsten/xeus-javascript#18]
You may try https://mryinglee.github.io/xeus-javascript/lab/index.html?path=OpenAI_testing.ipynb.

After clearing the output of all cells, if you run all cells, you may find the console.log() of cell A could appear in the output of cell B.
![image](https://github.com/jupyter-xeus/xeus-javascript/assets/11193534/19569edf-23c7-4021-a852-1bc6c3ebca22)

My fork didn't change any source code of this repo.

Please check,
Thanks.

**Comment by DerThorsten** [comment]
you are not awaiting your "ask" function.
If you want the async functions to print properly, just await them.
Ie `await ask("Please give an example of Javascript.");`
