### ISSUE TITLE
Fix the deploy step

### ISSUE THREAD

**Issue by jtpio** [DerThorsten/xeus-javascript#2]
As noticed in https://github.com/DerThorsten/xeus-javascript/pull/1#issuecomment-1900443240, the `deploy` step failed when opening a PR from a fork:

![image](https://github.com/DerThorsten/xeus-javascript/assets/591645/0d08a978-0260-4d71-af5b-a316acc58ca0)

Maybe the workflow can be adjusted to put the `if:` condition earlier in the workflow definition.

**Comment by DerThorsten** [comment]
done in #9

**Comment by jtpio** [comment]
Thanks!
