### ISSUE TITLE
Why don't borrow code from xeus-python?

### ISSUE THREAD

**Issue by MRYingLEE** [DerThorsten/xeus-javascript#20]
I found some good utilities functions (cpp) in https://github.com/jupyter-xeus/xeus-python. So, I thought I could borrow them to this repo.
But then a crazy idea was raised that maybe we can inherit xeus-javascript from xeus-python for most code of xeus-python can be borrowed.

Any idea?

**Comment by DerThorsten** [comment]
no xeus-javascript cannot inherit from xeus-python but feel free to take code from xeus-python and integrate it here.
PRs are welcom
