### ISSUE TITLE
"UnkwownError" happened for a line of "var"

### ISSUE THREAD

**Issue by MRYingLEE** [DerThorsten/xeus-javascript#23]
```JavaScript
var _Comm_id, _Comm_protocol_version_minor;
```
met "UnkwownError: ":
![image](https://github.com/jupyter-xeus/xeus-javascript/assets/11193534/ab445104-ac47-4733-b8c7-2e8e97d50483)

But, if I split the statement into 2 lines:

```JavaScript
var _Comm_id;
var _Comm_protocol_version_minor;
```
there is no error.

If I split the cell into 2, no error also.

Most likely it is a bug. Please check.

**Comment by DerThorsten** [comment]
fixed once #25 lands
