### ISSUE TITLE
“ReferenceError: require is not defined” error in the browser environment because of the require() method.

### ISSUE THREAD

**Issue by himgupta128** [DerThorsten/xeus-javascript#28]
I am trying to establish connection with bigquery from jupyterlite javascript -version 0.2.3 (https://jupyter-xeus.github.io/xeus-javascript/lab/index.html).
At very first stage, I am trying to import Google Cloud client library using below command which have 'require' function.
const {
ConnectionServiceClient,
} = require('@google-cloud/bigquery-connection');

// Creates a client
const client = new ConnectionServiceClient();

**But getting an error 'ReferenceError: require is not defined'****

Is there any workaround for 'require()' method?

![Script_output_console](https://github.com/jupyter-xeus/xeus-javascript/assets/93113113/3734ccf3-c96b-4c5c-90b4-191f511eefbd)

**Comment by DerThorsten** [comment]
You can probably use the import statement instead of the require statement

**Comment by himgupta128** [comment]
I tried to use import but the when I am creating a client below error is coming.
'TypeError: ConnectionServiceClient is not a constructor'.

Command used:
// Imports the Google Cloud client library
const {
  ConnectionServiceClient,
} = import('@google-cloud/bigquery-connection');

// Creates a client
const client = new ConnectionServiceClient();
