### ISSUE TITLE
Bug: The cell execution does not wait for the final output

### ISSUE THREAD

**Issue by MRYingLEE** [DerThorsten/xeus-javascript#32]
In your built-in xeus-javascript.ipynb, if I run the first cells quickly, then I will meet the following issue:
![image](https://github.com/jupyter-xeus/xeus-javascript/assets/11193534/90093247-4fe9-475e-ab73-c33acafbfea5)

According to my memory, it is a new issue, which does not happen in versions of a few weeks ago.

Please check. 

Thank you,

**Comment by DerThorsten** [comment]
thanks for reporting this. its a bit nasty that there are no automated unit tests. This is why bugs like that are sneaking in.

I try to fix this these days

**Comment by DerThorsten** [comment]
fixed with #33
